#
# Copyright (c) 2021 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# BT
CONFIG_BT=y

CONFIG_BT_CENTRAL=y
CONFIG_BT_PERIPHERAL=y

CONFIG_BT_SCAN=y
CONFIG_BT_SCAN_FILTER_ENABLE=y
CONFIG_BT_SCAN_NAME_CNT=1
CONFIG_BT_SCAN_MANUFACTURER_DATA_CNT=1
CONFIG_BT_SCAN_WITH_IDENTITY=y
CONFIG_BT_ID_MAX=1

CONFIG_BT_EXT_ADV=y

CONFIG_BT_DEVICE_NAME="nRF_DM"
CONFIG_BT_DDFS=y

# Distance Measurement
CONFIG_DM_MODULE=y

CONFIG_MPSL=y
CONFIG_MPSL_TIMESLOT_SESSION_COUNT=1

CONFIG_DM_MODULE_LOG_LEVEL_DBG=n
CONFIG_DM_GPIO_DEBUG=y
CONFIG_PWM=y

CONFIG_NCS_SAMPLES_DEFAULTS=y
CONFIG_DK_LIBRARY=y

CONFIG_DM_HIGH_PRECISION_CALC=y

CONFIG_UART_CONSOLE=n
CONFIG_USE_SEGGER_RTT=y
CONFIG_CONSOLE=y
CONFIG_RTT_CONSOLE=y

# Disable the standard UART console to avoid conflicts
# Optional: Enable the shell backend for interactive commands
CONFIG_SHELL=y
CONFIG_SHELL_RTT_LOG_LEVEL_DBG=y
CONFIG_SHELL_BACKEND_RTT=y
CONFIG_SHELL_BACKEND_SERIAL=n
CONFIG_GPIO=y


#CONFIG_GNSS_SATELLITES=y
CONFIG_MODEM=y
#CONFIG_GNSS_U_BLOX_M8=y
#CONFIG_GNSS=y
CONFIG_SERIAL=y
CONFIG_UART_ASYNC_API=y
CONFIG_UART_INTERRUPT_DRIVEN=y


CONFIG_SPI=y
CONFIG_SPI_ASYNC=y
CONFIG_LORA=y
CONFIG_DMA=y
CONFIG_LORA_LOG_LEVEL_DBG=n
CONFIG_LORA_SHELL=y
CONFIG_LOG_PRINTK=y
CONFIG_PRINTK=y


CONFIG_LOG=y
CONFIG_LOG_BUFFER_SIZE=8192
#CONFIG_GNSS_DUMP_TO_LOG=y
#CONFIG_GNSS_DUMP_TO_LOG_BUF_SIZE=4096
#CONFIG_GNSS_LOG_LEVEL_DBG=y
#CONFIG_MODEM_MODULES=y
#CONFIG_MODEM_MODULES_LOG_LEVEL_DBG=y
CONFIG_BT_HCI_CORE_LOG_LEVEL_DBG=n
#CONFIG_DM_TIMESLOT_OVERHEAD_US=300